apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otep-webs-cert
spec:
  secretName: otep-webs-cert
  dnsNames:
    - {{ .Values.domainOtepWeb }}
  issuerRef:
    name: lets-encrypt-issuer-prod
    kind: ClusterIssuer
    group: cert-manager.io

# TODO : ให้ uncomment ตรงนี้ออกเมื่อต้องการใช้โดเมนที่สอง production (รอ otep ชี้โดเมนก่อน)
#{{- if eq .Values.envGroup "prod" }}
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: otep-webs-cert2
#spec:
#  secretName: otep-webs-cert2
#  dnsNames:
#    - {{ .Values.domainOtepWeb2 }}
#  issuerRef:
#    name: lets-encrypt-issuer-prod
#    kind: ClusterIssuer
#    group: cert-manager.io
#{{- end }}
