---
envAlias: development
envAliasJob: Development
domainOtepAPI: api-dev.otep.triple-t.co
domainOtepWeb: web-dev.otep.triple-t.co
envGroup: dev

domainOtepAPI2: notused-dev.otep.go.th
domainOtepWeb2: notused.otep.go.th
