otep-apis:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 800m
        memory: 1024Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: ENV_GROUP
        value: 'prod'

      - name: TEMP_DIR
        value: '/data/temp'

      - name: PORT
        value: '3001'

      - name: NODE_ENV
        value: 'production'

      - name: CORS_ORIGINS
        value: 'http://localhost:5173,https://web.otep.triple-t.co,https://ddc.otep.go.th'

      - name: MAX_FILE_SIZE
        value: '10485760'

      - name: DEBUG
        value: 'false'

      - name: DB_HOST
        value: 'postgresql.postgresql-prod.svc.cluster.local'

      - name: DB_PORT
        value: '5432'

      - name: DB_USER
        value: 'postgres'

      - name: DB_NAME
        value: 'otep-prod'

      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: otep-postgres-secret
            key: adminPasswordKey
            optional: false

      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: JWT_SECRET
            optional: false

      - name: SESSION_SECRET
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: SESSION_SECRET
            optional: false

      ### SMTP ###
      - name: SMTP_HOST
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: SMTP_HOST
            optional: false

      - name: SMTP_USER
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: SMTP_USER
            optional: false

      - name: SMTP_PASS
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: SMTP_PASS
            optional: false

      #- name: SMTP_REQUIRE_TLS
      #  value: 'false'

      - name: SMTP_PORT
        value: '587'

      - name: SMTP_SECURE
        value: 'false'

      - name: EMAIL_FROM
        value: 'OTEP System <ddc@otep.go.th>'

      - name: OTP_SEND_EMAIL
        value: 'true'
