otep-apis:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: ENV_GROUP
        value: 'prod'

      - name: TEMP_DIR
        value: '/data/temp'

      - name: PORT
        value: '3001'

      - name: NODE_ENV
        value: 'production'

      - name: CORS_ORIGIN
        value: 'http://localhost:5173,https://web.otep.triple-t.co'

      - name: MAX_FILE_SIZE
        value: '10485760'

      - name: DEBUG
        value: 'false'

      - name: DB_HOST
        value: 'postgresql.postgresql-prod.cluster.cluster.local'

      - name: DB_PORT
        value: '5432'

      - name: DB_USER
        value: 'postgres'

      - name: DB_NAME
        value: 'otep-prod'

      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: otep-postgres-secret
            key: adminPasswordKey
            optional: false

      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: JWT_SECRET
            optional: false

      - name: SESSION_SECRET
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: SESSION_SECRET
            optional: false
