otep-apis:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 800m
        memory: 1024Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      - name: ENV_GROUP
        value: 'dev'

      - name: TEMP_DIR
        value: '/data/temp'

      - name: PORT
        value: '3001'

      - name: NODE_ENV
        value: 'development'

      - name: CORS_ORIGINS
        value: 'http://localhost:5173,https://web-dev.otep.triple-t.co'

      - name: MAX_FILE_SIZE
        value: '10485760'

      - name: DEBUG
        value: 'true'


      - name: DB_HOST
        value: 'postgresql.postgresql-dev.svc.cluster.local'

      - name: DB_PORT
        value: '5432'

      - name: DB_USER
        value: 'postgres'

      - name: DB_NAME
        value: 'otep-dev'

      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: otep-postgres-secret
            key: adminPasswordKey
            optional: false

      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: JWT_SECRET
            optional: false

      - name: SESSION_SECRET
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: SESSION_SECRET
            optional: false

      ### SMTP ###
      - name: SMTP_HOST
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: SMTP_HOST_NEW
            optional: false

      - name: SMTP_USER
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: SMTP_USER
            optional: false

      - name: SMTP_PASS
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: SMTP_PASS_NEW
            optional: false

      #- name: SMTP_REQUIRE_TLS
      #  value: 'false'

      - name: SMTP_PORT
        value: '587'

      - name: SMTP_SECURE
        value: 'false'

      - name: EMAIL_FROM
        value: 'OTEP System (Test) <ddc@otep.go.th>'

      - name: OTP_SEND_EMAIL
        value: 'true' #'false'

      ##### Thai ID
      - name: THAID_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: THAID_CLIENT_ID
            optional: false

      - name: THAID_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: THAID_CLIENT_SECRET
            optional: false

      - name: THAID_API_KEY
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: THAID_API_KEY
            optional: false
      
      - name: THAID_REDIRECT_URI
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: THAID_REDIRECT_URI
            optional: false

      - name: FRONTEND_URL
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: FRONTEND_URL
            optional: false


      ##### EDU
      - name: EDUID_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: EDUID_CLIENT_ID
            optional: false

      - name: EDUID_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: EDUID_CLIENT_SECRET
            optional: false

      - name: EDUID_BASE_URL
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: EDUID_BASE_URL
            optional: false
      
      - name: EDUID_REDIRECT_URI
        valueFrom:
          secretKeyRef:
            name: otep-secret
            key: EDUID_REDIRECT_URI
            optional: false
