apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otep-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: otep-secret       # name of the k8s Secret to be created
  data:
  {{- if eq .Values.envGroup "prod" }}
  - secretKey: JWT_SECRET
    remoteRef:
      key: initial-secret
      property: JWT_SECRET_PROD
  - secretKey: SESSION_SECRET
    remoteRef:
      key: initial-secret
      property: SESSION_SECRET_PROD
  {{- else if eq .Values.envGroup "dev" }}
  - secretKey: JWT_SECRET
    remoteRef:
      key: initial-secret
      property: JWT_SECRET_DEV
  - secretKey: SESSION_SECRET
    remoteRef:
      key: initial-secret
      property: SESSION_SECRET_DEV

  # Thai ID
  - secretKey: THAID_CLIENT_ID
    remoteRef:
      key: initial-secret
      property: DEV_THAID_CLIENT_ID

  - secretKey: THAID_CLIENT_SECRET
    remoteRef:
      key: initial-secret
      property: DEV_THAID_CLIENT_SECRET

  - secretKey: THAID_API_KEY
    remoteRef:
      key: initial-secret
      property: DEV_THAID_API_KEY

  - secretKey: THAID_REDIRECT_URI
    remoteRef:
      key: initial-secret
      property: DEV_THAID_REDIRECT_URI

  - secretKey: FRONTEND_URL
    remoteRef:
      key: initial-secret
      property: DEV_FRONTEND_URL

  {{- end }}

  - secretKey: SMTP_HOST
    remoteRef:
      key: initial-secret
      property: SMTP_HOST

  - secretKey: SMTP_USER
    remoteRef:
      key: initial-secret
      property: SMTP_USER

  - secretKey: SMTP_PASS
    remoteRef:
      key: initial-secret
      property: SMTP_PASS

  - secretKey: SMTP_PASS_NEW
    remoteRef:
      key: initial-secret
      property: SMTP_PASS_NEW

  - secretKey: SMTP_HOST_NEW
    remoteRef:
      key: initial-secret
      property: SMTP_HOST_NEW
