apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otep-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: otep-secret       # name of the k8s Secret to be created
  data:
  {{- if eq .Values.envGroup "prod" }}
  - secretKey: JWT_SECRET
    remoteRef:
      key: initial-secret
      property: JWT_SECRET_PROD
  - secretKey: SESSION_SECRET
    remoteRef:
      key: initial-secret
      property: SESSION_SECRET_PROD
  {{- else if eq .Values.envGroup "dev" }}
  - secretKey: JWT_SECRET
    remoteRef:
      key: initial-secret
      property: JWT_SECRET_DEV
  - secretKey: SESSION_SECRET
    remoteRef:
      key: initial-secret
      property: SESSION_SECRET_DEV
  {{- end }}
