apiVersion: batch/v1
kind: CronJob
metadata:
  name: document-extract
spec:
  # kubectl create job --from=cronjob/document-extract document-extract-001 -n otep-production
  suspend: true
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
          - name: cron-script
            image: "pjamenaja/otep-jobs:{{ .Values.otepJobs.imageTag }}"
            imagePullPolicy: IfNotPresent
            command:
            - ruby
            args:
            - /scripts/document-extract.rb
            env:
            - name: PG_HOST
              value: postgresql.postgresql-{{ .Values.envGroup }}.svc.cluster.local

            - name: PG_PORT
              value: "5432"

            - name: PG_USER
              value: "postgres"

            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: otep-postgres-secret
                  key: adminPasswordKey
                  optional: false

            - name: PG_DB
              value: "otep-{{ .Values.envGroup }}"

            - name: TEMP_DIR
              value: '/data/temp'

            volumeMounts:
            - name: temp-dir
              mountPath: /data/temp

            - name: secrets
              readOnly: true
              mountPath: "/secrets"

          restartPolicy: OnFailure

          volumes:
          - name: temp-dir
            emptyDir: {}

          - name: secrets
            secret:
              secretName: gcp-sa-secret
